; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32
framework = arduino

; --- Configuraciones para NeoSense AI ---

; Velocidad del monitor serial para ver los "print" de depuración sin basura
monitor_speed = 115200
upload_speed = 115200

; Librerías necesarias para el proyecto
lib_deps = 
    m5stack/M5Unified @ ^0.1.12      ; Controla la pantalla, colores y botones
    bblanchon/ArduinoJson @ ^6.21.3  ; Extrae los datos (Temp, Hum) del JSON del backend